Update currency-build.yaml

diff --git a/.github/workflows/currency-build.yaml b/.github/workflows/currency-build.yaml
--- a/.github/workflows/currency-build.yaml
+++ b/.github/workflows/currency-build.yaml
@@ -66,9 +66,7 @@ jobs:
           
       - name: Install Python dependencies
         run: |
-          sudo apt-get install -y python3-pip
-          python3 -m pip install --force-reinstall -v "requests==2.31.0"
-          python3 -m pip install --upgrade docker
+          sudo apt-get install -y python3-requests
 
       - name: Get Build Info and Save Variables
         run: |
@@ -99,30 +97,30 @@ jobs:
         with:
           name: variable-sh
 
-      - name: Install Docker
-        run: |
-          echo "Installing docker ..........................................."
-          curl -fsSL https://get.docker.com -o get-docker.sh
-          sudo sh get-docker.sh
+      # - name: Install Docker
+      #   run: |
+      #     echo "Installing docker ..........................................."
+      #     curl -fsSL https://get.docker.com -o get-docker.sh
+      #     sudo sh get-docker.sh
 
-      - name: Start Docker with vfs storage driver
-        run: |
-          sudo systemctl stop docker || true
-          sudo killall dockerd || true
-          echo '{"storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json > /dev/null
-          sudo dockerd > /tmp/dockerd.log 2>&1 &
-          for i in {1..10}; do
-            if docker info > /dev/null 2>&1; then
-              echo "Docker is up"
-              break
-            fi
-            sleep 3
-          done
-          if ! docker info > /dev/null 2>&1; then
-            echo "Docker failed to start. Dumping logs:"
-            cat /tmp/dockerd.log
-            exit 1
-          fi
+      # - name: Start Docker with vfs storage driver
+      #   run: |
+      #     sudo systemctl stop docker || true
+      #     sudo killall dockerd || true
+      #     echo '{"storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json > /dev/null
+      #     sudo dockerd > /tmp/dockerd.log 2>&1 &
+      #     for i in {1..10}; do
+      #       if docker info > /dev/null 2>&1; then
+      #         echo "Docker is up"
+      #         break
+      #       fi
+      #       sleep 3
+      #     done
+      #     if ! docker info > /dev/null 2>&1; then
+      #       echo "Docker failed to start. Dumping logs:"
+      #       cat /tmp/dockerd.log
+      #       exit 1
+      #     fi
     
       - name: Build Package
         run: |
