Update pr-build.yaml

diff --git a/.github/workflows/pr-build.yaml b/.github/workflows/pr-build.yaml
--- a/.github/workflows/pr-build.yaml
+++ b/.github/workflows/pr-build.yaml
@@ -27,9 +27,8 @@ run-name: >
       || github.event.pull_request.title }}
 
 jobs:
-  validate:
+  build_info:
     runs-on: ${{ github.event_name == 'pull_request' && 'ubuntu-24.04-ppc64le-p10' || inputs.large-runner }}
-
     steps:
       - name: Checkout code (Pull Request)
         if: github.event_name == 'pull_request'
@@ -41,41 +40,115 @@ jobs:
         with:
           ref: refs/pull/${{ inputs.pr_number }}/head
 
-      - name: Install required packages
+      - name: Install system packages
         run: |
           sudo apt update -y
-          sudo apt-get install -y file
+          sudo apt install -y jq file
 
       - name: Install Python dependencies
         run: |
           pip3 install --force-reinstall -v "requests==2.31.0"
           pip3 install --upgrade docker
-
+  
       - name: Set PR number
         run: echo "PR_NUMBER=${{ github.event.pull_request.number || inputs.pr_number }}" >> $GITHUB_ENV
 
-      - name: Run validate_builds.py script with live logs
+
+      - name: Locate and parse build_info.json
         run: |
-          python3 -u gha-script/validate_builds.py ${PR_NUMBER:-false} 2>&1 | tee build_log
-          my_pid_status=${PIPESTATUS[0]}
+          BUILD_INFO_FILE=$(find . -name "build_info.json" -print -quit)
 
-          build_size=$(stat -c %s build_log)
-
-          if [ "$my_pid_status" -ne 0 ]; then
-            echo "Script failed for PR #${PR_NUMBER}"
-            if [ "$build_size" -lt 1800000 ]; then
-              cat build_log
-            else
-              echo "Build log too large, showing last 100 lines"
-              tail -100 build_log
-            fi
+          if [ -z "$BUILD_INFO_FILE" ]; then
+            echo "build_info.json not found!"
             exit 1
-          else
-            echo "Script completed successfully for PR #${PR_NUMBER}"
-            if [ "$build_size" -lt 1800000 ]; then
-              cat build_log
-            else
-              echo "Build log too large, showing last 100 lines"
-              tail -100 build_log
-            fi
           fi
+
+          echo "Using build_info: $BUILD_INFO_FILE"
+
+          PACKAGE_NAME=$(jq -r '.package_name // ""' $BUILD_INFO_FILE)
+          VERSION=$(jq -r '.version // ""' $BUILD_INFO_FILE)
+
+          if [ -z "$PACKAGE_NAME" ] || [ -z "$VERSION" ]; then
+            echo "PACKAGE_NAME or VERSION missing in build_info.json"
+            exit 1
+          fi
+
+          echo "PACKAGE_NAME=$PACKAGE_NAME"
+          echo "VERSION=$VERSION"
+
+          # Export for next step
+          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+      - name: Read build_info.json
+        run: |
+          chmod +x ./gha-script/read_buildinfo.sh
+          bash ./gha-script/read_buildinfo.sh || true
+
+      - name: Create scanner-env.sh
+        run: |
+          mkdir -p package-cache
+
+          BUILD_INFO_FILE=$(find . -name "build_info.json" -print -quit)
+
+          echo "Using build_info: $BUILD_INFO_FILE"
+
+          PACKAGE_DIR=$(jq -r '.package_dir // ""' $BUILD_INFO_FILE)
+          WHEEL_BUILD=$(jq -r '.wheel_build // "false"' $BUILD_INFO_FILE)
+          DOCKER_BUILD=$(jq -r '.docker_build // "false"' $BUILD_INFO_FILE)
+          VALIDATE_BUILD=$(jq -r '.validate_build_script // "true"' $BUILD_INFO_FILE)
+
+
+          cat <<EOF > package-cache/scanner-env.sh
+          export PACKAGE_NAME=$PACKAGE_NAME
+          export VERSION=$VERSION
+          export PACKAGE_DIR=$PACKAGE_DIR
+          export WHEEL_BUILD=$WHEEL_BUILD
+          export BUILD_DOCKER=$DOCKER_BUILD
+          export VALIDATE_BUILD_SCRIPT=$VALIDATE_BUILD
+          EOF
+
+          mv variable.sh package-cache/ || true
+          echo "scanner-env.sh created"
+          cat package-cache/scanner-env.sh
+
+      - name: Archive package cache
+        run: tar -czf package-cache.tar.gz package-cache/
+
+      - name: Upload package cache
+        uses: actions/upload-artifact@v6
+        with:
+           name: package-cache
+           path: package-cache.tar.gz
+
+  # build:
+  #   needs: build_info
+  #   runs-on: ${{ github.event_name == 'pull_request' && 'ubuntu-24.04-ppc64le-p10' || inputs.large-runner }}
+  #   steps:
+  #     - uses: actions/checkout@v6
+
+  #     - name: Download package-cache
+  #       uses: actions/download-artifact@v7
+  #       with:
+  #         name: package-cache
+
+  #     - name: Extract package cache
+  #       run: tar -xzf package-cache.tar.gz
+
+  #     - name: Build package with logging
+  #       run: |
+  #         source package-cache/variable.sh || true
+  #         source package-cache/scanner-env.sh
+
+  #         bash ./gha-script/build_package.sh 2>&1 | tee build_log
+  #         status=${PIPESTATUS[0]}
+  #         size=$(stat -c %s build_log)
+
+  #         if [ "$status" -ne 0 ]; then
+  #           echo "Build failed"
+  #           [ "$size" -lt 1800000 ] && cat build_log || tail -100 build_log
+  #           exit 1
+  #         else
+  #           echo "Build succeeded"
+  #           [ "$size" -lt 1800000 ] && cat build_log || tail -100 build_log
+  #         fi
